/* main.c generated by valac 0.16.0, the Vala compiler
 * generated from main.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <glib/gi18n-lib.h>
#include <gtk/gtk.h>

#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))



void _vala_main (gchar** args, int args_length1);
static void _vala_array_add1 (GOptionEntry** array, int* length, int* size, const GOptionEntry* value);


static void _vala_array_add1 (GOptionEntry** array, int* length, int* size, const GOptionEntry* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (GOptionEntry, *array, *size);
	}
	(*array)[(*length)++] = *value;
}


void _vala_main (gchar** args, int args_length1) {
	FILE* _tmp0_;
	FILE* _tmp1_;
	const gchar* _tmp2_ = NULL;
	GOptionEntry* entries;
	gint entries_length1;
	gint _entries_size_;
	GOptionEntry _tmp3_ = {0};
	GOptionEntry terminator;
	GOptionEntry* _tmp4_;
	gint _tmp4__length1;
	GOptionEntry _tmp5_;
	FILE* _tmp11_;
	const gchar* _tmp12_ = NULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = stdout;
	fprintf (_tmp0_, "%s\n", GETTEXT_PACKAGE);
	_tmp1_ = stdout;
	_tmp2_ = _ ("Hello World!\n");
	fprintf (_tmp1_, "%s", _tmp2_);
	entries = NULL;
	entries_length1 = 0;
	_entries_size_ = entries_length1;
	_tmp3_.long_name = NULL;
	_tmp3_.short_name = (gchar) 0;
	_tmp3_.flags = 0;
	_tmp3_.arg = 0;
	_tmp3_.arg_data = NULL;
	_tmp3_.description = NULL;
	_tmp3_.arg_description = NULL;
	terminator = _tmp3_;
	_tmp4_ = entries;
	_tmp4__length1 = entries_length1;
	_tmp5_ = terminator;
	_vala_array_add1 (&entries, &entries_length1, &_entries_size_, &_tmp5_);
	{
		const gchar* _tmp6_ = NULL;
		GOptionEntry* _tmp7_;
		gint _tmp7__length1;
		_tmp6_ = _ ("[FILE]");
		_tmp7_ = entries;
		_tmp7__length1 = entries_length1;
		gtk_init_with_args (&args_length1, &args, _tmp6_, _tmp7_, GETTEXT_PACKAGE, &_inner_error_);
		if (_inner_error_ != NULL) {
			goto __catch0_g_error;
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		FILE* _tmp8_;
		GError* _tmp9_;
		const gchar* _tmp10_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp8_ = stdout;
		_tmp9_ = e;
		_tmp10_ = _tmp9_->message;
		fprintf (_tmp8_, "error %s\n", _tmp10_);
		_g_error_free0 (e);
	}
	__finally0:
	if (_inner_error_ != NULL) {
		entries = (g_free (entries), NULL);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp11_ = stdout;
	_tmp12_ = _ ("Hello World!\n");
	fprintf (_tmp11_, "%s", _tmp12_);
	entries = (g_free (entries), NULL);
}


int main (int argc, char ** argv) {
	g_thread_init (NULL);
	g_type_init ();
	_vala_main (argv, argc);
	return 0;
}



