/* main.c generated by valac 0.16.0, the Vala compiler
 * generated from main.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <augeas.h>
#include <stdlib.h>
#include <string.h>


#define TYPE_AUG_VALA_TEST (aug_vala_test_get_type ())
#define AUG_VALA_TEST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_AUG_VALA_TEST, AugValaTest))
#define AUG_VALA_TEST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_AUG_VALA_TEST, AugValaTestClass))
#define IS_AUG_VALA_TEST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_AUG_VALA_TEST))
#define IS_AUG_VALA_TEST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_AUG_VALA_TEST))
#define AUG_VALA_TEST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_AUG_VALA_TEST, AugValaTestClass))

typedef struct _AugValaTest AugValaTest;
typedef struct _AugValaTestClass AugValaTestClass;
typedef struct _AugValaTestPrivate AugValaTestPrivate;
#define _aug_close0(var) ((var == NULL) ? NULL : (var = (aug_close (var), NULL)))

struct _AugValaTest {
	GObject parent_instance;
	AugValaTestPrivate * priv;
};

struct _AugValaTestClass {
	GObjectClass parent_class;
};


static gpointer aug_vala_test_parent_class = NULL;

GType aug_vala_test_get_type (void) G_GNUC_CONST;
enum  {
	AUG_VALA_TEST_DUMMY_PROPERTY
};
void aug_vala_test_test_match (void);
void aug_vala_test_main (gchar** args, int args_length1);
static void _aug_vala_test_test_match_gcallback (void);
AugValaTest* aug_vala_test_new (void);
AugValaTest* aug_vala_test_construct (GType object_type);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static gchar** vala_aug_match (augeas* self, const gchar* path, int* result_length1) {
	gchar** result = NULL;
	gchar** matches = NULL;
	gint matches_length1 = 0;
	gint _matches_size_ = 0;
	const gchar* _tmp0_;
	gchar** _tmp1_ = NULL;
	gint _tmp2_ = 0;
	gint len;
	gchar** _tmp3_;
	gint _tmp3__length1;
	gchar** _tmp6_;
	gint _tmp6__length1;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (path != NULL, NULL);
	_tmp0_ = path;
	_tmp2_ = aug_match (self, _tmp0_, &_tmp1_);
	matches = (_vala_array_free (matches, matches_length1, (GDestroyNotify) g_free), NULL);
	matches = _tmp1_;
	matches_length1 = -1;
	_matches_size_ = matches_length1;
	len = _tmp2_;
	_tmp3_ = matches;
	_tmp3__length1 = matches_length1;
	if (_tmp3_ != NULL) {
		gint _tmp4_;
		gint _tmp5_;
		_tmp4_ = len;
		matches_length1 = _tmp4_;
		_tmp5_ = matches_length1;
	}
	_tmp6_ = matches;
	_tmp6__length1 = matches_length1;
	if (result_length1) {
		*result_length1 = _tmp6__length1;
	}
	result = _tmp6_;
	return result;
}


void aug_vala_test_test_match (void) {
	augeas* _tmp0_;
	augeas* aug;
	gint _tmp1_ = 0;
	gchar** _tmp2_ = NULL;
	gchar** res;
	gint res_length1;
	gint _res_size_;
	_tmp0_ = aug_init (NULL, NULL, AUG_NONE);
	aug = _tmp0_;
	_tmp2_ = vala_aug_match (aug, "/files/etc/passwd", &_tmp1_);
	res = _tmp2_;
	res_length1 = _tmp1_;
	_res_size_ = res_length1;
	g_assert (res != NULL);
	g_assert (res_length1 == 1);
	res = (_vala_array_free (res, res_length1, (GDestroyNotify) g_free), NULL);
	_aug_close0 (aug);
}


static void _aug_vala_test_test_match_gcallback (void) {
	aug_vala_test_test_match ();
}


void aug_vala_test_main (gchar** args, int args_length1) {
	g_test_init (&args_length1, &args, NULL);
	g_test_add_func ("/aug/vala/match", _aug_vala_test_test_match_gcallback);
	g_test_run ();
}


int main (int argc, char ** argv) {
	g_thread_init (NULL);
	g_type_init ();
	aug_vala_test_main (argv, argc);
	return 0;
}


AugValaTest* aug_vala_test_construct (GType object_type) {
	AugValaTest * self = NULL;
	self = (AugValaTest*) g_object_new (object_type, NULL);
	return self;
}


AugValaTest* aug_vala_test_new (void) {
	return aug_vala_test_construct (TYPE_AUG_VALA_TEST);
}


static void aug_vala_test_class_init (AugValaTestClass * klass) {
	aug_vala_test_parent_class = g_type_class_peek_parent (klass);
}


static void aug_vala_test_instance_init (AugValaTest * self) {
}


GType aug_vala_test_get_type (void) {
	static volatile gsize aug_vala_test_type_id__volatile = 0;
	if (g_once_init_enter (&aug_vala_test_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AugValaTestClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) aug_vala_test_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AugValaTest), 0, (GInstanceInitFunc) aug_vala_test_instance_init, NULL };
		GType aug_vala_test_type_id;
		aug_vala_test_type_id = g_type_register_static (G_TYPE_OBJECT, "AugValaTest", &g_define_type_info, 0);
		g_once_init_leave (&aug_vala_test_type_id__volatile, aug_vala_test_type_id);
	}
	return aug_vala_test_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



